name: Build userscript
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: userscript
          path: dist/wm-toolkit.*.js
