name: Attach assets to release
on:
  release:
    types: published
jobs:
  release:
    - uses: actions/download-artifact@v2
      with:
        name: userscript
    - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./wm-toolkit.user.js
          asset_name: wm-toolkit.user.js
    - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./wm-toolkit.meta.js
          asset_name: wm-toolkit.meta.js
